name: hashpass
description: HashPass é um software desenvolvido para guardar senhas de qualquer serviço ou aplicativo de forma criptografada.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  validatorless: ^1.2.1
  crypto: ^3.0.1
  encrypt: ^5.0.1
  flutter_aes_ecb_pkcs5: ^0.1.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  archive: ^3.2.1
  font_awesome_flutter: ^10.4.0
  google_mobile_ads: ^3.0.0
  url_launcher: ^6.0.20
  file_picker: ^5.2.11
  jaguar_jwt: ^3.0.0
  device_info_plus: ^8.2.2
  intl: ^0.18.0
  get: ^4.6.5
  provider: ^6.0.5
  share_plus: ^7.0.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  path: ^1.8.0
  local_auth: ^2.1.6
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sql/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
